Concordium/cryptox-ios

- ConcordiumWallet/Features/DefaultAccountCIS2Token/DefaultCIS2TokenManager.swift
Remove USDT, USDC, ETH, and WBTC from default tokens.
> Remove Arabella default tokens

- CryptoX.xcodeproj/xcshareddata/xcschemes/ProdMainNet.xcscheme
- CryptoX.xcodeproj/xcshareddata/xcschemes/ProdTestNet.xcscheme
Add build pre-actions for the Xcode cloud to be able to find secret API keys during build.
> add build pre actions

- CryptoX.xcodeproj/xcshareddata/xcschemes/ProdMainNet.xcscheme
- CryptoX.xcodeproj/xcshareddata/xcschemes/ProdTestNet.xcscheme
Place pre-build config file in the right place
> Place pre-build config file in the right place

- CryptoX.xcodeproj/project.pbxproj
- CryptoX.xcodeproj/xcshareddata/xcschemes/ProdTestNet.xcscheme
- ci_scripts/ci_pre_xcodebuild.sh
Add pre build script, so XCode cloud can successfully build an app(hope this works).
> Add pre build script

- ioscommon/Base/AppConstants.swift
> add missing return

- CHANGELOG.md
- CryptoX.xcodeproj/project.pbxproj
> Release 3.2.2 preparation

- ConcordiumWallet/Features/OnrampFlow/WertWidgetManager.swift
> Fix WertIO widget

- CHANGELOG.md
- CryptoX.xcodeproj/project.pbxproj
- WAL-867 Earn flow_keyboard input field bug
- WAL-867 Earn flow bug
- WAL-856 Create separate local package - replacing legacy mobile wallet lib
> WAL-886 Release 3.3.3

- CHANGELOG.md
- ConcordiumWallet/Features/MoreSection/More.storyboard
All social links leads to TG.
Fix link images tags.
> Fix social links

- CHANGELOG.md
- ConcordiumWallet/Features/MoreSection/MoreMenuViewController.swift
- ConcordiumWallet/Features/NewAccountFlow/HomeScreen/HomeScreenView.swift
- Buy button from main screen
- NFT items from more settings view
> Release 3.3.3 build 49

- CryptoX.xcodeproj/project.pbxproj
- include missing `Concordium` dependency into release build schema
> Release 3.3.6

- ConcordiumWallet/Core/CoreData/CoreDataPLTStore.swift
- ConcordiumWallet/Features/NewAccountFlow/AccountTokenListView.swift
- ConcordiumWallet/Features/NewAccountFlow/ManageTokensView.swift
- ConcordiumWallet/Features/NewAccountFlow/TokenBalanceView.swift
- ConcordiumWallet/Resources/Colors.xcassets/accent_secondary.colorset/Contents.json
Add ability to manage PLT tokens:
- remove the tokens
> add ability to manage PLT tokens

- ConcordiumWallet/Features/AccountDetail/AccountDetailView.swift
- ConcordiumWallet/Features/NewAccountFlow/AccountTokenListView.swift
Fix cells switching on the account token list view
> fix cells switching on the account token list view

- ConcordiumWallet/Features/NewAccountFlow/AccountTokenListView.swift
- ConcordiumWallet/Features/PLTTokenSupport/CoreData/CoreDataPLTStore.swift
- ConcordiumWallet/Service/AccountsService.swift
- CryptoXDataModel.xcdatamodeld/CryptoXDataModel.xcdatamodel/contents
Fix bug with removing of the PLT tokens.
> fix bug with plt token removing

- CHANGELOG.md
- ConcordiumWallet/Core/PushNotifications/NotificationTokenService.swift
- ConcordiumWallet/Core/PushNotifications/TransactionNotificationService.swift
- ConcordiumWallet/Features/AccountDetail/AccountDetailView.swift
- ConcordiumWallet/Features/AccountsMainView/AccountsMainRouter.swift
- ConcordiumWallet/Features/AccountsMainView/ViewModels/AccountPreviewViewModel.swift
- ConcordiumWallet/Features/AccountsMainView/ViewModels/AccountsMainViewModel.swift
- ConcordiumWallet/Features/AccountsMainView/Views/AccountInfoView.swift
- ConcordiumWallet/Features/MoreSection/Notifications/NotificationsView.swift
- ConcordiumWallet/Features/NewOnboardingFlow/WelcomeView.swift
- ConcordiumWallet/Features/OnrampFlow/CCDOnrampView.swift
- ConcordiumWallet/Resources/en.lproj/Localizable.strings
- ConcordiumWallet/Views/RootView/MainTabBarController.swift
User is able to receive notifications about received PLTs.
Show notification popup on the welcome screen for the users which hasn't allowed the notifications and also show it on settings notifications section with same conditions.
> add possibility to receive notifications for PLT

- ConcordiumWallet/Core/Navigation/NavigationDestinationBuilder.swift
- ConcordiumWallet/Features/CIS2TokenSupport/ImportToken/Models/SearchTokenViewModel.swift
- ConcordiumWallet/Features/CIS2TokenSupport/ImportToken/Views/AddTokenView.swift
- ConcordiumWallet/Features/CIS2TokenSupport/ImportToken/Views/TokenView.swift
- ConcordiumWallet/Features/NewAccountFlow/AccountTokenListView.swift
Fix bugs:
-  save search state when user returns from token details on add token screen;
- fixed search of the CIS-2 tokens
> Fix plt related bugs

- ConcordiumWallet/Features/NewAccountFlow/TokenBalanceView.swift
Make send/receive buttons active for the PLTs which are not in the deny list.
> Make send/receive buttons active

- ConcordiumWallet/Core/PushNotifications/NotificationTokenService.swift
- ConcordiumWallet/Features/AccountDetail/AccountDetailView.swift
- ConcordiumWallet/Features/CIS2TokenSupport/ImportToken/Models/ImportTokenViewModel.swift
- ConcordiumWallet/Features/CIS2TokenSupport/ImportToken/Models/SearchTokenViewModel.swift
- ConcordiumWallet/Features/CIS2TokenSupport/ImportToken/Views/AddTokenView.swift
- ConcordiumWallet/Features/CIS2TokenSupport/ImportToken/Views/TokenView.swift
- ConcordiumWallet/Features/NewAccountFlow/AccountTokenListView.swift
- ConcordiumWallet/Features/NewAccountFlow/TokenBalanceView.swift
- ConcordiumWallet/Features/NewAccountFlow/TokenDetailsView.swift
- ConcordiumWallet/Features/PLTTokenSupport/PLTTokenService.swift
- ConcordiumWallet/Features/PLTTokenSupport/TokenFetcher.swift
- ConcordiumWallet/Features/PLTTokenSupport/UnifiedToken.swift
- ConcordiumWallet/Features/TransferTokenFlow/Views/ChooseTokenView.swift
- ConcordiumWallet/Model/AutoGenerated/AccountPLTToken.swift
Handle the PLT token metadata properly.
> The wallet must show PLT Description and Thumbnail from metadata

- ConcordiumWallet/Features/PLTTokenSupport/CoreData/CoreDataPLTStore.swift
- ConcordiumWallet/Service/AccountsService.swift
- ConcordiumWallet/Settings/AppSettings.swift
- Fix paused tokens handling
- Fetch all PLTs balances for account when app is running for the first time
> Fix paused tokens handling

- ConcordiumWallet/Features/TransferTokenFlow/Models/CIS2TokenTransferModel.swift
- ConcordiumWallet/Features/TransferTokenFlow/Models/TransferTokenViewModel.swift
- ConcordiumWallet/Features/TransferTokenFlow/Views/ChooseTokenView.swift
- ConcordiumWallet/Features/TransferTokenFlow/Views/SendTokenCell.swift
- ConcordiumWallet/Features/TransferTokenFlow/Views/SendTokenView.swift
Show PLT token icon on send screen
> Show PLT token icon on send screen

- ConcordiumWallet/Features/AccountDetail/TokenFormatter.swift
- ConcordiumWallet/Features/NewAccountFlow/AccountTokenListView.swift
- ConcordiumWallet/Features/NewAccountFlow/TokenBalanceView.swift
Show minimum 2 decimals for PLT tokens
> fix decimals for PLT token balance

- ConcordiumWallet/Core/PushNotifications/NotificationTokenService.swift
- ConcordiumWallet/Core/PushNotifications/TransactionNotificationService.swift
- ConcordiumWallet/Features/Account/AccountDetails/AccountTransactionsData/TransactionViewModel.swift
- ConcordiumWallet/Features/AccountDetail/TokenFormatter.swift
- ConcordiumWallet/Features/NewAccountFlow/AccountTokenListView.swift
- ConcordiumWallet/Features/NewAccountFlow/TokenBalanceView.swift
- ConcordiumWallet/Features/TransferTokenFlow/Views/SendTokenCell.swift
Fixed PLTs amount displaying. Fixed placeholder size on the send token cell.
> PLTs fixup
